### PR TITLE
Capitalize "Requesting resend of blocks around you" and move it to the action bar

### PR DESCRIPTION
**Pull request by OneYellowLemon**
Capitalize "Requesting resend of blocks around you" message and move it to the action bar to avoid cluttering chat. In my opinion, the message looks much better in the action bar, and then it doesn't stick around clogging up your chat. I also capitalized any message that didn't start with a capital letter.

### CODE REVIEW

**Comment by OneYellowLemon** [comment]
@gbl Would you be able to take a look and accept/reject this PR?

**Comment by gbl** [comment]
I basically agree with the request, moving the text from chat to the action bar is a good idea. There will be some players who won't notice the action bar and complain that "nothing happens anymore", but I guess you can't accomodate everybody.

As to the translation texts, their "source" is on crowdin.com, and the language files will get overwritten with each `gradle downloadTranslations` run which is part of the build process. So, I'll accept the PR as it is right now, but expect the capitalization to disappear unless the crowdin translations get updated as well.

**Comment by OneYellowLemon** [comment]
Ah, got it. I'll go see if I can update them on Crowdin.

**Comment by OneYellowLemon** [comment]
@gbl Turns out someone has already suggestion to capitalize them on Crowdin.

**Pull request merged**
